; PlatformIO Project Configuration File
; Drive Assistant — Waveshare ESP32-S3-Touch-AMOLED-1.8 (V1 SH8601 & V2 CO5300)

[env:esp32-s3-devkitc-1]
platform = espressif32@6.9.0
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
build_src_filter = +<*.cpp> +<screens/*.cpp>
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_type = opi
build_flags = 
	-D BOARD_HAS_PSRAM
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1
lib_deps = 
	h2zero/NimBLE-Arduino@^2.5.1
	moononournation/GFX Library for Arduino@1.4.7
	lewisxhe/XPowersLib@^0.3.3
	lewisxhe/SensorLib@^0.5.0
